[package]
name = "orml-benchmarking"
description = "Provide macro to benchmark Substrate runtime."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/benchmarking"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
linregress = "0.1"
paste = "0.1"
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
sp-api = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }
sp-runtime-interface = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }
sp-runtime = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }
sp-std = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }
sp-io = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }
frame-support = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }
frame-system = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }
frame-benchmarking = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-alpha.8" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-runtime-interface/std",
	"sp-runtime/std",
	"sp-api/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
]

